### ISSUE TITLE
Site using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by marissarousseau** [swoodmood/Sapplycompass#4]
Currently the site loads in HTTP, which is a privacy concern for people who uses the site. 

![](https://i.imgur.com/EPgR2Re.jpg)

Some browsers completely block the site due to this privacy issue and lack of HTTPS. I know this project appears to be dead, but you can change the GitHub Pages settings for this repo to enforce HTTPS very easily. Just go to this repo's settings and scroll to GitHub Pages settings.

**Comment by swoodmood** [comment]
The site isn't even up anymore dude

**Comment by marissarousseau** [comment]
Is http://sapplypoliticalcompass.com a fork someone else made? The results page contains a link directing to this repository. My bad if it's a fork hosted by someone else.

**Comment by swoodmood** [comment]
That's someone else's fork
